### ISSUE TITLE
'$ vagrant halt' produces error: (Bundler::GemfileNotFound)

### ISSUE THREAD

**Issue by alexidro** [ChrisWiegman/Primary-Vagrant#51]
Hi, I followed all the steps and everything is working fine, just when I do vagrant halt I get the following error and I have to shutdown the VM manually from the VirtualBox GUI and so the triggers are not working as intended.
I'm on Ubuntu 15.10, Virtualbox 5.0.4, Vagrant 1.7.4
Thank You in advance! Ciaooo

<pre>
alessandro@NB-Alex:~/PV$ vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c /var/vagrant/bin/vagrant_halt"...
==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:194:in `root'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `bundle_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:439:in `configure_gem_home'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:431:in `configure_gem_home_and_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `configure'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:153:in `definition'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `setup'
==> default: 	from /usr/bin/vagrant:75:in `<main>'
==> default: Command execution finished.
The command "vagrant ssh -c '/var/vagrant/bin/vagrant_halt'" returned a failed exit code. The
error output is shown below:

/usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler.rb:194:in `root'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `bundle_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:439:in `configure_gem_home'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:431:in `configure_gem_home_and_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `configure'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:153:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `setup'
	from /usr/bin/vagrant:75:in `<main>'
</pre>

**Comment by michaelbeil** [comment]
were you already SSHed into the box?

**Comment by alexidro** [comment]
no, I do nothing, but doing same thing on a Windows machine (so nothing just vagrant up and vagrant halt) turns in all done without errors. Am I missing something?

**Comment by alexidro** [comment]
this is my complete output:
<pre>
alessandro@NB-Alex:~/PV$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
==> default: Machine booted and ready!
GuestAdditions 5.0.4 running --- OK.
==> default: Checking for guest additions in VM...
==> default: Checking for host entries
==> default: Checking for host entries
==> default: Setting hostname...
==> default: Configuring and enabling network interfaces...
==> default: Mounting shared folders...
    default: /vagrant => /home/alessandro/PV
    default: /var/www/pv => /home/alessandro/PV/www/default/pv
    default: /var/xdebug => /home/alessandro/PV/xdebug
    default: /var/vagrant/bin => /home/alessandro/PV/bin
    default: /etc/apache2/ssl => /home/alessandro/PV/ssl
    default: /var/vagrant/conf => /home/alessandro/PV/conf
    default: /var/vagrant/mysql => /home/alessandro/PV/mysql
    default: /var/www/webgrind.pv => /home/alessandro/PV/www/default/webgrind
    default: /var/www/replacedb.pv => /home/alessandro/PV/www/default/Search-Replace-DB
    default: /var/www/aboutnews.it => /home/alessandro/Webdev/aboutnews.it/www
    default: /var/www/phpmyadmin.pv => /home/alessandro/PV/www/default/phpmyadmin
    default: /var/www/core.wordpress.pv => /home/alessandro/PV/www/default/wordpress/core
    default: /var/www/trunk.wordpress.pv => /home/alessandro/PV/www/default/wordpress/trunk
    default: /var/www/stable.wordpress.pv => /home/alessandro/PV/www/default/wordpress/stable
    default: /var/www/legacy.wordpress.pv => /home/alessandro/PV/www/default/wordpress/legacy
    default: /var/www/trunk.wordpress.pv/htdocs/content => /home/alessandro/PV/www/default/wordpress/content
    default: /var/www/stable.wordpress.pv/htdocs/content => /home/alessandro/PV/www/default/wordpress/content
    default: /var/www/legacy.wordpress.pv/htdocs/content => /home/alessandro/PV/www/default/wordpress/content
    default: /tmp/vagrant-puppet/modules-3cb889f18b52b0716e9f8abc39cd7a24 => /home/alessandro/PV/modules
    default: /tmp/vagrant-puppet/manifests-a11d1078b1b1f2e3bdea27312f6ba513 => /home/alessandro/PV/manifests
==> default: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> default: flag to force provisioning. Provisioners marked to run always will still run.
==> default: Running provisioner: puppet...
==> default: Running Puppet with init.pp...
==> default: stdin: is not a tty
==> default: Notice: Compiled catalog for pv in environment production in 4.91 seconds
==> default: Notice: /Stage[main]/Main/File[/var/www/phpmyadmin.pv/phpmyadmin/config.inc.php]/owner: owner changed 'www-data' to 'root'
==> default: Notice: /Stage[main]/Main/File[/var/www/phpmyadmin.pv/phpmyadmin/config.inc.php]/group: group changed 'vagrant' to 'root'
==> default: Notice: /Stage[main]/Composer/Exec[composer-update]/returns: executed successfully
==> default: Notice: /Stage[main]/Apache/Service[apache]/ensure: ensure changed 'stopped' to 'running'
==> default: Notice: Finished catalog run in 12.28 seconds
alessandro@NB-Alex:~/PV$ vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c /var/vagrant/bin/vagrant_halt"...
==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:194:in `root'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `bundle_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:439:in `configure_gem_home'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:431:in `configure_gem_home_and_path'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `configure'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:153:in `definition'
==> default: 	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `setup'
==> default: 	from /usr/bin/vagrant:75:in `<main>'
==> default: Command execution finished.
The command "vagrant ssh -c '/var/vagrant/bin/vagrant_halt'" returned a failed exit code. The
error output is shown below:

/usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
	from /usr/lib/ruby/vendor_ruby/bundler.rb:194:in `root'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:106:in `bundle_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:439:in `configure_gem_home'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:431:in `configure_gem_home_and_path'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:92:in `configure'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:153:in `definition'
	from /usr/lib/ruby/vendor_ruby/bundler.rb:123:in `setup'
	from /usr/bin/vagrant:75:in `<main>'

alessandro@NB-Alex:~/PV$ 

</pre>

**Comment by ChrisWiegman** [comment]
Ah ha. Something with your Ruby is causing it. Make sure your gems are up to date.

**Comment by altrovideo** [comment]
Hi , I'm using Debian https://wiki.debian.org/DebianStretch with  Vagrant 1.7.4 for wordpress vvv
and I have the same error:
```
root@debian:~/vagrant-local# vagrant halt
==> default: Running triggers before halt...
==> default: Executing command "vagrant ssh -c vagrant_halt"...
==> default: /usr/lib/ruby/vendor_ruby/bundler.rb:198:in `rescue in root': Could not locate Gemfile or .bundle/ directory (Bundler::GemfileNotFound)
```

I've solved only with 

    vagrant ssh
    sudo su
    shutdown -h now
